FILE-13 - Add more test coverage
filecoin-saturn/L1-dashboard pull request #57
Opened 2023-08-24 09:59 UTC by gitstart

### What does this PR do?

- Add more unit test coverage
- Add more e2e test coverage 

### Issue reference

https://github.com/filecoin-saturn/L1-dashboard/issues/50

### Demo video/scrennshot:

**Added unit tests for each component**
![image](https://github.com/GitStartHQ/client-filecoin-saturn/assets/42426067/f54f6e64-4034-44a9-9d3f-df880b1e76d1)

**Added E2E test for app**
![image](https://github.com/GitStartHQ/client-filecoin-saturn/assets/42426067/067f427a-e431-4ec2-ae69-93c2799fbab3)

**Added E2E test for WebUi mode**

![image](https://github.com/GitStartHQ/client-filecoin-saturn/assets/42426067/6a8e4395-d179-4255-b4d2-848ad1540ecb)

###  Demo E2E
https://www.loom.com/share/c1fa9d4d5cfd418badf6b4f0e93ad38d

### Coverage snapshot
![image](https://github.com/GitStartHQ/client-filecoin-saturn/assets/42426067/957ede70-48f5-410a-b336-01346331f24a)
![image](https://github.com/GitStartHQ/client-filecoin-saturn/assets/42426067/ee48aff8-7b37-4899-9ead-e134ab4775d0)

> This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.

2023-08-24 12:44 UTC, gitstart commented
####`env` for `webui` 

- VITE_ROOT_DOMAIN
- VITE_METRICS_ORIGIN
- VITE_STATS_ORIGIN
- VITE_MODE_WEBUI

#### `env` for `embed` mode

- VITE_ROOT_DOMAIN
- VITE_METRICS_ORIGIN
- VITE_STATS_ORIGIN

2023-08-29 09:46 UTC, gitstart commented
@guanzo this PR is ready for review

2023-08-30 08:46 UTC, juliangruber requested changes
These new tests are great!

I'm just wondering about the stability of this project - will adding tests with this level of detail slow down the project, or speed it up?

2023-08-30 08:46 UTC, juliangruber commented on src/pages/stats/index.tsx
> +    <div data-testid="stats-grid" className="h-full">
Is adding `.h-full` related to tests?

2023-08-30 08:47 UTC, juliangruber commented on src/pages/stats/index.tsx
> +    <div data-testid="stats-grid" className="h-full">
nvm I see this is because it used to be a fragment. I trust this will render exactly the same?

2023-08-30 16:46 UTC, DiegoRBaquero reviewed
Not really familiar with FE or its testing, but, a lot of these assertions seem to be just asserting what the code is telling it to be. If we define button to have a width of X why would it be Y on the test?

2023-08-31 11:26 UTC, gitstart commented on src/pages/stats/index.tsx
> +    <div data-testid="stats-grid" className="h-full">
Yes this would not distort the view at all

2023-08-31 11:29 UTC, gitstart commented
> Not really familiar with FE or its testing, but, a lot of these assertions seem to be just asserting what the code is telling it to be. If we define button to have a width of X why would it be Y on the test?

Thank you for the question. The test is of two kinds, an e2e test and a unit test The e2e test uses Puppeteer to ensure that the features work from end to end on the browser and no new additions break existing features. Same as the unit test. It ensures that it renders as expected with the appropriate parameters and that future additions would not cause breaking changes.

2023-11-07 10:08 UTC, closed without merging